### ISSUE TITLE
Add optdepends

### ISSUE THREAD

**Issue by Ste74** [FadeMind/Manjarin#1]
Hi , do you think if adding the adapta-maia-theme for use the adapta-nokto-maia shell theme and the papirus maia icon theme like @paullinuxthemer say in the announcement ? :wink: 

I can grab your pkgbuild since the one build by Philip is now broken in download

**Comment by FadeMind** [comment]
Check mailbox and feel free made proper change. :smiley:

**Comment by Ste74** [comment]
Thank you my friend .. :smile:
