### ISSUE TITLE
Do new manjaro logo

### ISSUE THREAD

**Issue by Ste74** [FadeMind/Manjarin#2]
@paullinuxthemer new manjaro logo is a square can you change this in square
https://github.com/FadeMind/manjarin-gtk-theme/blob/master/gtk-3.0/objects/other/Drive.png
:wink:

**Comment by paullinuxthemer** [comment]
I will.  Soon...

**Comment by Ste74** [comment]
Thank you :+1: good job :wink:

**Comment by paullinuxthemer** [comment]
Sorry for this stupid question: I have a new version of the Drive.png.  How do I change it?

**Comment by paullinuxthemer** [comment]
![drive](https://user-images.githubusercontent.com/26058111/39410617-5f2ef596-4bfb-11e8-9e23-df34596116a0.png)

You do not see it but just right above this text is a attached file with the correct drive.png

**Comment by Ste74** [comment]
You have write access here, you can navigate in the folder here and upload new file i.e. do the commit :wink:

**Comment by paullinuxthemer** [comment]
Allright, I seem to have managed it.

**Comment by paullinuxthemer** [comment]
Also made a new screenshot with the new logo and uploaded it here.  The new theme is also available at gnome-look.org with the correct screenshot and logo

**Comment by Ste74** [comment]
Thank you :smile:
